/**
 * Verilog DSL Parser for Electronom Engineering CAD
 *
 * Parses the controlled Verilog subset generated by our exporter.
 * This is NOT a full IEEE-1364 parser — it only handles:
 *   - module / endmodule
 *   - wire declarations
 *   - parameterized module instantiations (and parameterless ones)
 *   - comment-based annotations (network, waypoints, canvas size, edge metadata)
 */

import type { EngineeringConnectionKind, EngineeringEdge, EngineeringNodeType, EngineeringTermination, NetworkConfig } from '../graph'

/* ------------------------------------------------------------------ */
/*  AST types                                                         */
/* ------------------------------------------------------------------ */

export interface VerilogWireAST {
  name: string
  /** Extracted from wire name pattern `w_<edgeId>_<conductor>` */
  edgeId: string
  /** Validated conductor kind; absent when the source declares none */
  conductor?: EngineeringConnectionKind
  /** Edge type from `type=` pair (or legacy `conductor=power`-style tokens) */
  edgeType?: NonNullable<EngineeringEdge['type']>
  /** Source node id parsed from preceding comment */
  source?: string
  /** Target node id parsed from preceding comment */
  target?: string
  /** Wire-end terminations parsed from `sterm=`/`tterm=` pairs */
  sourceTermination?: EngineeringTermination
  targetTermination?: EngineeringTermination
  /** Drawing waypoints parsed from `// route: [...]` comment (mm) */
  waypoints?: Array<{ x: number; y: number }>
}

export interface VerilogInstanceAST {
  /** e.g. `el_mcb` */
  moduleName: string
  /** e.g. `mcb_1` */
  instanceName: string
  /** All `.PARAM(value)` pairs */
  params: Map<string, string | number>

  /* Convenience fields extracted from params: */
  nodeId: string
  nodeType: EngineeringNodeType
  label: string
  xMm?: number
  yMm?: number
  rotation?: 0 | 90 | 180 | 270
}

export interface VerilogAST {
  /** Module name after `module` keyword */
  moduleName: string
  /** Extracted from `// graphId=...` comment */
  graphId: string
  /** Extracted from `// draftId=...` comment */
  draftId: string
  /** Extracted from `// name: ...` comment */
  name?: string
  /** Extracted from `// locale: ...` comment */
  locale?: 'uk' | 'ru'
  /** Extracted from `// network: phase=..., voltage_v=..., input_a=..., earthing=...` */
  network?: Partial<NetworkConfig>
  /** Extracted from `// canvas: WxH` comment */
  canvasSizeMm?: { width: number; height: number }
  wires: VerilogWireAST[]
  instances: VerilogInstanceAST[]
}

export interface VerilogParseError {
  line: number
  message: string
}

export interface VerilogParseResult {
  ast: VerilogAST | null
  errors: VerilogParseError[]
}

/* ------------------------------------------------------------------ */
/*  Known node types (module name → EngineeringNodeType)              */
/* ------------------------------------------------------------------ */

const MODULE_TO_NODE_TYPE: Record<string, EngineeringNodeType> = {
  el_grid_input: 'grid_input',
  el_meter: 'meter',
  el_main_breaker: 'main_breaker',
  el_voltage_relay: 'voltage_relay',
  el_surge_protection: 'surge_protection',
  el_busbar_n: 'busbar_n',
  el_busbar_pe: 'busbar_pe',
  el_rcd: 'rcd',
  el_mcb: 'mcb',
  el_cable_line: 'cable_line',
  el_load: 'load',
  el_generator: 'generator',
  el_inverter: 'inverter',
  el_battery: 'battery',
  el_ats: 'ats',
  el_distribution_panel: 'distribution_panel',
  el_terminal: 'terminal',
}

const CONDUCTOR_KINDS = new Set<EngineeringConnectionKind>([
  'L', 'N', 'PE', 'PEN', 'DC+', 'DC-', 'signal', 'bus',
])

/** Wire-name suffix token → conductor (DC+/DC- are encoded as DCp/DCm in identifiers) */
const WIRE_TOKEN_TO_CONDUCTOR: Record<string, EngineeringConnectionKind> = {
  L: 'L',
  N: 'N',
  PE: 'PE',
  PEN: 'PEN',
  DCp: 'DC+',
  DCm: 'DC-',
  signal: 'signal',
  bus: 'bus',
}

const EDGE_TYPES = new Set<NonNullable<EngineeringEdge['type']>>([
  'power', 'control', 'earth', 'neutral', 'signal', 'bus', 'dc',
])

const EARTHING_SYSTEMS = new Set<NetworkConfig['earthingSystem']>(['TN-S', 'TN-C-S', 'TT', 'IT'])

const TERMINATIONS = new Set<EngineeringTermination>(['direct', 'twist', 'ferrule', 'lug', 'clamp'])

/* ------------------------------------------------------------------ */
/*  Regex patterns                                                    */
/* ------------------------------------------------------------------ */

/** Matches `module <name>;` */
const RE_MODULE = /^\s*module\s+(\w+)\s*;/

/** Matches `wire <name>;` */
const RE_WIRE = /^\s*wire\s+(\w+)\s*;/

/** Matches `// edge <edgeId>: <source> -> <target>` with optional `, key=value` pairs */
const RE_EDGE_COMMENT = /^\s*\/\/\s*edge\s+(\S+):\s*(\S+)\s*->\s*([^,\s]+)(.*)$/

/** Builds a fresh `key=value` pair matcher (fresh instance: global regexes share lastIndex) */
function keyValuePairRe() {
  return /(\w+)=([^,\s]+)/g
}

/** Matches `// route: [(x,y), ...]` */
const RE_ROUTE_COMMENT = /^\s*\/\/\s*route:\s*\[(.+)\]/

/** Matches a parameterized instantiation start: `el_type #(...` */
const RE_INSTANCE_START = /^\s*(el_\w+)\s+#\(/

/** Matches a parameterless instantiation: `el_type instance_name ();` */
const RE_INSTANCE_NOPARAM = /^\s*(el_\w+)\s+(\w+)\s*\(\s*\)\s*;/

/** Matches `// graphId=<value>` */
const RE_GRAPH_ID = /^\s*\/\/\s*graphId=(.+)/

/** Matches `// draftId=<value>` */
const RE_DRAFT_ID = /^\s*\/\/\s*draftId=(.+)/

/** Matches `// name: <value>` */
const RE_NAME = /^\s*\/\/\s*name:\s*(.+)/

/** Matches `// locale: <value>` */
const RE_LOCALE = /^\s*\/\/\s*locale:\s*(\S+)/

/** Matches `// network: key=value, ...` */
const RE_NETWORK = /^\s*\/\/\s*network:\s*(.+)/

/** Matches `// canvas: <W>mm x <H>mm` or `// canvas: <W>x<H>` */
const RE_CANVAS = /^\s*\/\/\s*canvas:\s*(\d+)\s*(?:mm\s*)?\s*x\s*(\d+)/i

/** Matches `.PARAM_NAME("string_value")` or `.PARAM_NAME(numeric_value)` */
const RE_PARAM = /\.(\w+)\(("(?:[^"\\]|\\.)*"|[\d.eE+-]+)\)/g

/* ------------------------------------------------------------------ */
/*  Parser implementation                                             */
/* ------------------------------------------------------------------ */

function parseParamValue(raw: string): string | number {
  if (raw.startsWith('"') && raw.endsWith('"')) {
    return raw.slice(1, -1).replace(/\\(["\\])/g, '$1')
  }
  const num = Number(raw)
  return Number.isFinite(num) ? num : raw
}

function parseWaypoints(raw: string): Array<{ x: number; y: number }> {
  const points: Array<{ x: number; y: number }> = []
  const re = /\(\s*(-?[\d.]+)\s*,\s*(-?[\d.]+)\s*\)/g
  let match: RegExpExecArray | null = re.exec(raw)
  while (match) {
    points.push({ x: Number(match[1]), y: Number(match[2]) })
    match = re.exec(raw)
  }
  return points
}

function parseNetworkComment(raw: string): Partial<NetworkConfig> {
  const network: Partial<NetworkConfig> = {}
  const re = keyValuePairRe()
  let match: RegExpExecArray | null = re.exec(raw)
  while (match) {
    const key = match[1] || ''
    const value = match[2] || ''
    if (key === 'phase') {
      const n = Number(value)
      if (n === 1 || n === 3) network.phase = n
    } else if (key === 'voltage_v') {
      const n = Number(value)
      if (n === 230 || n === 400) network.voltageV = n
    } else if (key === 'input_a') {
      const n = Number(value)
      if (Number.isFinite(n) && n > 0) network.inputBreakerA = n
    } else if (key === 'earthing') {
      if (EARTHING_SYSTEMS.has(value as NetworkConfig['earthingSystem'])) {
        network.earthingSystem = value as NetworkConfig['earthingSystem']
      }
    }
    match = re.exec(raw)
  }
  return network
}

/**
 * Extracts the full parameter block from a multi-line instantiation.
 * Parens inside string literals are ignored.
 */
function extractInstanceBlock(lines: string[], startIndex: number): {
  fullText: string
  endIndex: number
} | null {
  let depth = 0
  let text = ''
  for (let i = startIndex; i < lines.length; i++) {
    const line = lines[i]
    if (line === undefined) continue
    text += line + '\n'
    let inString = false
    let escaped = false
    for (const ch of line) {
      if (escaped) {
        escaped = false
        continue
      }
      if (ch === '\\') {
        escaped = true
        continue
      }
      if (ch === '"') {
        inString = !inString
        continue
      }
      if (inString) continue
      if (ch === '(') depth++
      if (ch === ')') depth--
    }
    // Instance ends when all parens are closed and we see `();`
    if (depth <= 0 && /\(\s*\)\s*;/.test(text)) {
      return { fullText: text, endIndex: i }
    }
  }
  return null
}

function inferConductorFromWireName(wireName: string): EngineeringConnectionKind | undefined {
  // Pattern: w_<edgeId>_<conductorToken>
  const lastUnderscore = wireName.lastIndexOf('_')
  if (lastUnderscore > 0) {
    const candidate = wireName.slice(lastUnderscore + 1)
    return WIRE_TOKEN_TO_CONDUCTOR[candidate]
  }
  return undefined
}

function inferEdgeIdFromWireName(wireName: string): string {
  // Pattern: w_<edgeId>_<conductorToken>
  // Remove 'w_' prefix and the last _conductorToken suffix
  const withoutPrefix = wireName.startsWith('w_') ? wireName.slice(2) : wireName
  const lastUnderscore = withoutPrefix.lastIndexOf('_')
  if (lastUnderscore > 0) {
    const candidate = withoutPrefix.slice(lastUnderscore + 1)
    if (WIRE_TOKEN_TO_CONDUCTOR[candidate] || candidate === 'power') {
      return withoutPrefix.slice(0, lastUnderscore)
    }
  }
  return withoutPrefix
}

interface PendingEdgeComment {
  edgeId: string
  source: string
  target: string
  conductor?: string
  type?: string
  sterm?: string
  tterm?: string
}

function buildInstance(
  moduleName: string,
  instanceName: string,
  params: Map<string, string | number>,
): VerilogInstanceAST {
  const nodeType = MODULE_TO_NODE_TYPE[moduleName]

  const nodeId = typeof params.get('NODE_ID') === 'string'
    ? params.get('NODE_ID') as string
    : instanceName

  const label = typeof params.get('LABEL') === 'string'
    ? params.get('LABEL') as string
    : nodeType?.replace(/_/g, ' ') ?? moduleName

  const xMm = typeof params.get('X_MM') === 'number' ? params.get('X_MM') as number : undefined
  const yMm = typeof params.get('Y_MM') === 'number' ? params.get('Y_MM') as number : undefined
  const rotation = typeof params.get('ROTATION') === 'number' ? params.get('ROTATION') as 0 | 90 | 180 | 270 : undefined

  const instance: VerilogInstanceAST = {
    moduleName,
    instanceName,
    params,
    nodeId,
    nodeType: nodeType ?? 'load',
    label,
  }
  if (xMm !== undefined) instance.xMm = xMm
  if (yMm !== undefined) instance.yMm = yMm
  if (rotation !== undefined) instance.rotation = rotation
  return instance
}

export function parseVerilogSource(source: string): VerilogParseResult {
  const lines = source.split('\n')
  const errors: VerilogParseError[] = []

  let moduleName = ''
  let graphId = ''
  let draftId = ''
  let name: string | undefined
  let locale: 'uk' | 'ru' | undefined
  let network: Partial<NetworkConfig> | undefined
  let canvasSizeMm: { width: number; height: number } | undefined
  const wires: VerilogWireAST[] = []
  const instances: VerilogInstanceAST[] = []

  // Pending metadata from comments preceding a wire/instance
  let pendingEdgeComment: PendingEdgeComment | null = null
  let pendingWaypoints: Array<{ x: number; y: number }> | null = null

  let i = 0
  while (i < lines.length) {
    const line = lines[i]
    if (line === undefined) {
      i++
      continue
    }
    const trimmed = line.trim()

    // Skip empty lines and endmodule
    if (!trimmed || trimmed === 'endmodule') {
      i++
      continue
    }

    // Module declaration
    const moduleMatch = RE_MODULE.exec(trimmed)
    if (moduleMatch) {
      moduleName = moduleMatch[1] || ''
      i++
      continue
    }

    // Comment: graphId
    const graphIdMatch = RE_GRAPH_ID.exec(trimmed)
    if (graphIdMatch) {
      graphId = (graphIdMatch[1] ?? '').trim()
      i++
      continue
    }

    // Comment: draftId
    const draftIdMatch = RE_DRAFT_ID.exec(trimmed)
    if (draftIdMatch) {
      draftId = (draftIdMatch[1] ?? '').trim()
      i++
      continue
    }

    // Comment: project name
    const nameMatch = RE_NAME.exec(trimmed)
    if (nameMatch) {
      const value = (nameMatch[1] ?? '').trim()
      if (value) name = value
      i++
      continue
    }

    // Comment: locale
    const localeMatch = RE_LOCALE.exec(trimmed)
    if (localeMatch) {
      const value = (localeMatch[1] ?? '').trim()
      if (value === 'uk' || value === 'ru') locale = value
      i++
      continue
    }

    // Comment: network config
    const networkMatch = RE_NETWORK.exec(trimmed)
    if (networkMatch) {
      network = parseNetworkComment(networkMatch[1] ?? '')
      i++
      continue
    }

    // Comment: canvas size
    const canvasMatch = RE_CANVAS.exec(trimmed)
    if (canvasMatch) {
      canvasSizeMm = { width: Number(canvasMatch[1] || 0), height: Number(canvasMatch[2] || 0) }
      i++
      continue
    }

    // Comment: edge metadata
    const edgeMatch = RE_EDGE_COMMENT.exec(trimmed)
    if (edgeMatch) {
      pendingEdgeComment = {
        edgeId: edgeMatch[1] || '',
        source: edgeMatch[2] || '',
        target: edgeMatch[3] || '',
      }
      const pairRe = keyValuePairRe()
      let pairMatch: RegExpExecArray | null = pairRe.exec(edgeMatch[4] ?? '')
      while (pairMatch) {
        const key = pairMatch[1] || ''
        const value = pairMatch[2] || ''
        if (key === 'conductor') pendingEdgeComment.conductor = value
        if (key === 'type') pendingEdgeComment.type = value
        if (key === 'sterm') pendingEdgeComment.sterm = value
        if (key === 'tterm') pendingEdgeComment.tterm = value
        pairMatch = pairRe.exec(edgeMatch[4] ?? '')
      }
      i++
      continue
    }

    // Comment: route waypoints
    const routeMatch = RE_ROUTE_COMMENT.exec(trimmed)
    if (routeMatch) {
      pendingWaypoints = parseWaypoints(routeMatch[1] || '')
      i++
      continue
    }

    // Skip other comments (including `// node ...` and `// This source ...`)
    if (trimmed.startsWith('//')) {
      i++
      continue
    }

    // Wire declaration
    const wireMatch = RE_WIRE.exec(trimmed)
    if (wireMatch) {
      const wireName = wireMatch[1] || ''

      let conductor: EngineeringConnectionKind | undefined
      let edgeType: NonNullable<EngineeringEdge['type']> | undefined

      if (pendingEdgeComment) {
        const rawConductor = pendingEdgeComment.conductor
        if (rawConductor && CONDUCTOR_KINDS.has(rawConductor as EngineeringConnectionKind)) {
          conductor = rawConductor as EngineeringConnectionKind
        } else if (rawConductor && EDGE_TYPES.has(rawConductor as NonNullable<EngineeringEdge['type']>)) {
          // Legacy sources wrote `conductor=power` for edges that only had a type
          edgeType = rawConductor as NonNullable<EngineeringEdge['type']>
        }
        const rawType = pendingEdgeComment.type
        if (rawType && EDGE_TYPES.has(rawType as NonNullable<EngineeringEdge['type']>)) {
          edgeType = rawType as NonNullable<EngineeringEdge['type']>
        }
      } else {
        conductor = inferConductorFromWireName(wireName)
      }

      const wire: VerilogWireAST = {
        name: wireName,
        edgeId: pendingEdgeComment?.edgeId ?? inferEdgeIdFromWireName(wireName),
      }
      if (conductor) wire.conductor = conductor
      if (edgeType) wire.edgeType = edgeType
      if (pendingEdgeComment?.source) wire.source = pendingEdgeComment.source
      if (pendingEdgeComment?.target) wire.target = pendingEdgeComment.target
      if (pendingEdgeComment?.sterm && TERMINATIONS.has(pendingEdgeComment.sterm as EngineeringTermination)) {
        wire.sourceTermination = pendingEdgeComment.sterm as EngineeringTermination
      }
      if (pendingEdgeComment?.tterm && TERMINATIONS.has(pendingEdgeComment.tterm as EngineeringTermination)) {
        wire.targetTermination = pendingEdgeComment.tterm as EngineeringTermination
      }
      if (pendingWaypoints) wire.waypoints = pendingWaypoints

      wires.push(wire)
      pendingEdgeComment = null
      pendingWaypoints = null
      i++
      continue
    }

    // Module instantiation with parameters
    const instanceMatch = RE_INSTANCE_START.exec(trimmed)
    if (instanceMatch) {
      const block = extractInstanceBlock(lines, i)
      if (!block) {
        errors.push({ line: i + 1, message: `Unclosed instance starting at line ${i + 1}` })
        i++
        continue
      }

      const modName = instanceMatch[1] || ''
      if (!MODULE_TO_NODE_TYPE[modName]) {
        errors.push({ line: i + 1, message: `Unknown module type: ${modName}` })
      }

      // Extract parameters
      const params = new Map<string, string | number>()
      let paramMatch: RegExpExecArray | null = RE_PARAM.exec(block.fullText)
      while (paramMatch) {
        params.set(paramMatch[1] || '', parseParamValue(paramMatch[2] || ''))
        paramMatch = RE_PARAM.exec(block.fullText)
      }

      // Extract instance name: `...) instance_name ();`
      const instNameMatch = /\)\s+(\w+)\s+\(\s*\)\s*;/.exec(block.fullText)
      const instanceName = instNameMatch?.[1] ?? `unknown_${instances.length}`

      instances.push(buildInstance(modName, instanceName, params))

      pendingEdgeComment = null
      pendingWaypoints = null
      i = block.endIndex + 1
      continue
    }

    // Module instantiation without parameters: `el_busbar_n busbar_1 ();`
    const noParamMatch = RE_INSTANCE_NOPARAM.exec(trimmed)
    if (noParamMatch) {
      const modName = noParamMatch[1] || ''
      if (!MODULE_TO_NODE_TYPE[modName]) {
        errors.push({ line: i + 1, message: `Unknown module type: ${modName}` })
      }
      instances.push(buildInstance(modName, noParamMatch[2] || `unknown_${instances.length}`, new Map()))

      pendingEdgeComment = null
      pendingWaypoints = null
      i++
      continue
    }

    // Unknown line
    i++
  }

  if (!moduleName) {
    errors.push({ line: 1, message: 'No module declaration found' })
  }

  const ast: VerilogAST = {
    moduleName,
    graphId,
    draftId,
    wires,
    instances,
  }
  if (name !== undefined) ast.name = name
  if (locale !== undefined) ast.locale = locale
  if (network !== undefined) ast.network = network
  if (canvasSizeMm) {
    ast.canvasSizeMm = canvasSizeMm
  }

  return {
    ast,
    errors,
  }
}
